name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: haithemsboui/sma-assistant-backend:latest
    
    - name: SSH to VPS and update container
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          docker pull haithemsboui/sma-assistant-backend:latest
          docker stop sma-assistant-backend || true
          docker rm sma-assistant-backend || true
          docker run -d --name sma-assistant-backend -p 80:8000 haithemsboui/sma-assistant-backend:latest
          for i in {1..10}; do
              status=$(docker inspect -f '{{.State.Running}}' sma-assistant-backend)
              if [ "$status" = "true" ]; then
              echo "sma-assistant-backend Container started successfully."
              exit 0
              else
              echo "Waiting for sma-assistant-backend container to start... ($i/10)"
              sleep 3
              fi
          done

          echo "sma-assistant-backend Container failed to start!"
          docker logs sma-assistant-backend
          exit 1
